{
    [ - ]   status: 200,
    [ - ]   statusText: 'OK',
    [ - ]   headers: AxiosHeaders {
    [ - ]     date: 'Wed, 01 Feb 2023 15:16:18 GMT',
    [ - ]     'content-type': 'application/json;charset=UTF-8',
    [ - ]     'transfer-encoding': 'chunked',
    [ - ]     connection: 'close',
    [ - ]     via: '1.1 vegur',
    [ - ]     'cf-cache-status': 'DYNAMIC',
    [ - ]     'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=MvoZkob8DPRXQBRY89JO61iHmoA1M2svqiMHoXK2kxPRowmf6o4GV2qnmcFop4ws6DM79RnBLtU7uA4XMPHq0r3iEqURLBNbBTjXKpr9dVebGrzehmeT%2B%2FardA9yMhrDDGJA%2B%2B8%3D"}],"group":"cf-nel","max_age":604800}',
    [ - ]     nel: '{"success_fraction": ,"report_to":"cf-nel","max_age":604800}',
    [ - ]     server: 'cloudflare',
    [ - ]     'cf-ray': '792ba5c018bdf9da-PRG',
    [ - ]     'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
    [ - ]   },
    [ - ]   config: {
    [ - ]     transitional: {
    [ - ]       silentJSONParsing: true,
    [ - ]       forcedJSONParsing: true,
    [ - ]       clarifyTimeoutError: false
    [ - ]     },
    [ - ]     adapter: [ 'xhr', 'http' ],
    [ - ]     transformRequest: [ [Function: transformRequest] ],
    [ - ]     transformResponse: [ [Function: transformResponse] ],
    [ - ]     timeout:  ,
    [ - ]     xsrfCookieName: 'XSRF-TOKEN',
    [ - ]     xsrfHeaderName: 'X-XSRF-TOKEN',
    [ - ]     maxContentLength: -1,
    [ - ]     maxBodyLength: -1,
    [ - ]     env: { FormData: [Function], Blob: null },
    [ - ]     validateStatus: [Function: validateStatus],
    [ - ]     headers: AxiosHeaders {
    [ - ]       Accept: 'application/json, text/plain, */*',
    [ - ]       'User-Agent': 'axios/1.3. ',
    [ - ]       'Accept-Encoding': 'gzip, compress, deflate, br'
    [ - ]     },
    [ - ]     method: 'get',
    [ - ]     url: 'https://api.chucknorris.io/jokes/random',
    [ - ]     data: undefined
    [ - ]   },
    [ - ]   request: <ref *1> ClientRequest {
    [ - ]     _events: [Object: null prototype] {
    [ - ]       abort: [Function (anonymous)],
    [ - ]       aborted: [Function (anonymous)],
    [ - ]       connect: [Function (anonymous)],
    [ - ]       error: [Function (anonymous)],
    [ - ]       socket: [Function (anonymous)],
    [ - ]       timeout: [Function (anonymous)],
    [ - ]       prefinish: [Function: requestOnPrefinish]
    [ - ]     },
    [ - ]     _eventsCount: 7,
    [ - ]     _maxListeners: undefined,
    [ - ]     outputData: [],
    [ - ]     outputSize:  ,
    [ - ]     writable: true,
    [ - ]     destroyed: true,
    [ - ]     _last: true,
    [ - ]     chunkedEncoding: false,
    [ - ]     shouldKeepAlive: false,
    [ - ]     maxRequestsOnConnectionReached: false,
    [ - ]     _defaultKeepAlive: true,
    [ - ]     useChunkedEncodingByDefault: false,
    [ - ]     sendDate: false,
    [ - ]     _removedConnection: false,
    [ - ]     _removedContLen: false,
    [ - ]     _removedTE: false,
    [ - ]     _contentLength:  ,
    [ - ]     _hasBody: true,
    [ - ]     _trailer: '',
    [ - ]     finished: true,
    [ - ]     _headerSent: true,
    [ - ]     _closed: true,
    [ - ]     socket: TLSSocket {
    [ - ]       _tlsOptions: [Object],
    [ - ]       _secureEstablished: true,
    [ - ]       _securePending: false,
    [ - ]       _newSessionPending: false,
    [ - ]       _controlReleased: true,
    [ - ]       secureConnecting: false,
    [ - ]       _SNICallback: null,
    [ - ]       servername: 'api.chucknorris.io',
    [ - ]       alpnProtocol: false,
    [ - ]       authorized: true,
    [ - ]       authorizationError: null,
    [ - ]       encrypted: true,
    [ - ]       _events: [Object: null prototype],
    [ - ]       _eventsCount: 9,
    [ - ]       connecting: false,
    [ - ]       _hadError: false,
    [ - ]       _parent: null,
    [ - ]       _host: 'api.chucknorris.io',
    [ - ]       _readableState: [ReadableState],
    [ - ]       _maxListeners: undefined,
    [ - ]       _writableState: [WritableState],
    [ - ]       allowHalfOpen: false,
    [ - ]       _sockname: null,
    [ - ]       _pendingData: null,
    [ - ]       _pendingEncoding: '',
    [ - ]       server: undefined,
    [ - ]       _server: null,
    [ - ]       ssl: null,
    [ - ]       _requestCert: true,
    [ - ]       _rejectUnauthorized: true,
    [ - ]       parser: null,
    [ - ]       _httpMessage: [Circular *1],
    [ - ]       write: [Function: writeAfterFIN],
    [ - ]       [Symbol(res)]: null,
    [ - ]       [Symbol(verified)]: true,
    [ - ]       [Symbol(pendingSession)]: null,
    [ - ]       [Symbol(async_id_symbol)]: 2296,
    [ - ]       [Symbol(kHandle)]: null,
    [ - ]       [Symbol(kSetNoDelay)]: false,
    [ - ]       [Symbol(lastWriteQueueSize)]:  ,
    [ - ]       [Symbol(timeout)]: null,
    [ - ]       [Symbol(kBuffer)]: null,
    [ - ]       [Symbol(kBufferCb)]: null,
    [ - ]       [Symbol(kBufferGen)]: null,
    [ - ]       [Symbol(kCapture)]: false,
    [ - ]       [Symbol(kBytesRead)]: 892,
    [ - ]       [Symbol(kBytesWritten)]: 189,
    [ - ]       [Symbol(connect-options)]: [Object],
    [ - ]       [Symbol(RequestTimeout)]: undefined
    [ - ]     },
    [ - ]     _header: 'GET /jokes/random HTTP/1.1\r\n' +
    [ - ]       'Accept: application/json, text/plain, */*\r\n' +
    [ - ]       'User-Agent: axios/1.3. \r\n' +
    [ - ]       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
    [ - ]       'Host: api.chucknorris.io\r\n' +
    [ - ]       'Connection: close\r\n' +
    [ - ]       '\r\n',
    [ - ]     _keepAliveTimeout:  ,
    [ - ]     _onPendingData: [Function: nop],
    [ - ]     agent: Agent {
    [ - ]       _events: [Object: null prototype],
    [ - ]       _eventsCount: 2,
    [ - ]       _maxListeners: undefined,
    [ - ]       defaultPort: 443,
    [ - ]       protocol: 'https:',
    [ - ]       options: [Object: null prototype],
    [ - ]       requests: [Object: null prototype] {},
    [ - ]       sockets: [Object: null prototype] {},
    [ - ]       freeSockets: [Object: null prototype] {},
    [ - ]       keepAliveMsecs: 1000,
    [ - ]       keepAlive: false,
    [ - ]       maxSockets: Infinity,
    [ - ]       maxFreeSockets: 256,
    [ - ]       scheduling: 'lifo',
    [ - ]       maxTotalSockets: Infinity,
    [ - ]       totalSocketCount:  ,
    [ - ]       maxCachedSessions: 100,
    [ - ]       _sessionCache: [Object],
    [ - ]       [Symbol(kCapture)]: false
    [ - ]     },
    [ - ]     socketPath: undefined,
    [ - ]     method: 'GET',
    [ - ]     maxHeaderSize: undefined,
    [ - ]     insecureHTTPParser: undefined,
    [ - ]     path: '/jokes/random',
    [ - ]     _ended: true,
    [ - ]     res: IncomingMessage {
    [ - ]       _readableState: [ReadableState],
    [ - ]       _events: [Object: null prototype],
    [ - ]       _eventsCount: 4,
    [ - ]       _maxListeners: undefined,
    [ - ]       socket: [TLSSocket],
    [ - ]       httpVersionMajor: 1,
    [ - ]       httpVersionMinor: 1,
    [ - ]       httpVersion: '1.1',
    [ - ]       complete: true,
    [ - ]       rawHeaders: [Array],
    [ - ]       rawTrailers: [],
    [ - ]       aborted: false,
    [ - ]       upgrade: false,
    [ - ]       url: '',
    [ - ]       method: null,
    [ - ]       statusCode: 200,
    [ - ]       statusMessage: 'OK',
    [ - ]       client: [TLSSocket],
    [ - ]       _consuming: true,
    [ - ]       _dumped: false,
    [ - ]       req: [Circular *1],
    [ - ]       responseUrl: 'https://api.chucknorris.io/jokes/random',
    [ - ]       redirects: [],
    [ - ]       [Symbol(kCapture)]: false,
    [ - ]       [Symbol(kHeaders)]: [Object],
    [ - ]       [Symbol(kHeadersCount)]: 24,
    [ - ]       [Symbol(kTrailers)]: null,
    [ - ]       [Symbol(kTrailersCount)]:  ,
    [ - ]       [Symbol(RequestTimeout)]: undefined
    [ - ]     },
    [ - ]     aborted: false,
    [ - ]     timeoutCb: null,
    [ - ]     upgradeOrConnect: false,
    [ - ]     parser: null,
    [ - ]     maxHeadersCount: null,
    [ - ]     reusedSocket: false,
    [ - ]     host: 'api.chucknorris.io',
    [ - ]     protocol: 'https:',
    [ - ]     _redirectable: Writable {
    [ - ]       _writableState: [WritableState],
    [ - ]       _events: [Object: null prototype],
    [ - ]       _eventsCount: 3,
    [ - ]       _maxListeners: undefined,
    [ - ]       _options: [Object],
    [ - ]       _ended: true,
    [ - ]       _ending: true,
    [ - ]       _redirectCount:  ,
    [ - ]       _redirects: [],
    [ - ]       _requestBodyLength:  ,
    [ - ]       _requestBodyBuffers: [],
    [ - ]       _onNativeResponse: [Function (anonymous)],
    [ - ]       _currentRequest: [Circular *1],
    [ - ]       _currentUrl: 'https://api.chucknorris.io/jokes/random',
    [ - ]       [Symbol(kCapture)]: false
    [ - ]     },
    [ - ]     [Symbol(kCapture)]: false,
    [ - ]     [Symbol(kNeedDrain)]: false,
    [ - ]     [Symbol(corked)]:  ,
    [ - ]     [Symbol(kOutHeaders)]: [Object: null prototype] {
    [ - ]       accept: [Array],
    [ - ]       'user-agent': [Array],
    [ - ]       'accept-encoding': [Array],
    [ - ]       host: [Array]
    [ - ]     }
    [ - ]   },
    [ - ]   data: {
    [ - ]     categories: [],
    [ - ]     created_at: '2020-01-05 13:42:28.143137',
    [ - ]     icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
    [ - ]     id: 'f3cBaAByRWaeKNggFJRivQ',
    [ - ]     updated_at: '2020-01-05 13:42:28.143137',
    [ - ]     url: 'https://api.chucknorris.io/jokes/f3cBaAByRWaeKNggFJRivQ',
    [ - ]     value: "It is possible to contract hepatitis from smelling one of Chuck Norris's farts."
    [ - ]   }
    [ - ] }